GEMINI_API_KEY="AIzaSyAAHaZms6JtQTrjfUi_mDSL6k37BAe6IpY"
GOOGLE_SERPER_API_KEY='1ab1610fcacec0c661b6938a6b041ddfadd8b811'
YOUTUBE_CREDENTIALS_PATH="youtube_credentials.json"
GMAIL_CREDENTIALS_PATH="credentials.json"
USER_EMAIL="your_email@gmail.com"
DATABASE_PATH = "nexus.db"
DEBUG_MODE = false
LOG_LEVEL = INFO
